[manifest]
version = "1.0.0"
dump_lua = true
priority = 100000000

# Big thank you to hastagguigui and OneSuchKeeper for the following patches!

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "if _front and _front.suit and (_front.value == 'Jack' or _front.value == 'Queen' or _front.value == 'King') then"
position = "at"
payload = "if _front and _front.suit then"
match_indent = true

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "self.METRICS = {"
position = "before"
payload = '''
G.COLLABS.pos['2'] = {x=0,y=0}
G.COLLABS.pos['3'] = {x=1,y=0}
G.COLLABS.pos['4'] = {x=2,y=0}
G.COLLABS.pos['5'] = {x=3,y=0}
G.COLLABS.pos['6'] = {x=4,y=0}
G.COLLABS.pos['7'] = {x=5,y=0}
G.COLLABS.pos['8'] = {x=6,y=0}
G.COLLABS.pos['9'] = {x=7,y=0}
G.COLLABS.pos['10'] = {x=8,y=0}
G.COLLABS.pos['Jack'] = {x=9,y=0}
G.COLLABS.pos['Queen'] = {x=10,y=0}
G.COLLABS.pos['King'] = {x=11,y=0}
G.COLLABS.pos['Ace'] = {x=12,y=0}
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local faces = {'K','Q','J'}"
position = "at"
payload = "local faces = {'A','K','Q','J','T','9','8','7','6','5','4','3','2'}"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "4*G.CARD_W,"
position = "at"
payload = "8*G.CARD_W,"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "for i = 1, 3 do"
position = "at"
payload = "for i = 1, #faces do"
match_indent = true